version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: 'parker'
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: 'parker'

  parker:
    build:
      dockerfile: Dockerfile
    environment:
      DATABASE_DBNAME: parker
      DATABASE_PASSWORD: 12345678
      DATABASE_USERNAME: parker
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      SERBER_PORT: 8000
    expose:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure
    links:
      - "db:database"
